name: Test vite (wait-on)

on: workflow_dispatch

jobs:
  standard:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: dependencies
      run: npm ci
    - name: start vite server
      run: npx vite &
    - name: wait for server
      # 10 second timeout
      run: npx wait-on http-get://localhost:5173 --config wait-on.config.json --timeout 10000 --verbose
    - name: netstat
      run: netstat -lnt | grep 5173
    - name: curl
      run: npm run curl
    - name: cypress Test
      run: npx cypress run
