name: Test vite (GHA)

on: workflow_dispatch

jobs:
  simple:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: dependencies
      run: npm ci
    - name: Test
      uses: cypress-io/github-action@v5
      with:
        start: npm run dev

  wait-on-built-in:
    strategy:
      fail-fast: false
      matrix:
        OS: [ubuntu-22.04, windows-2022, macos-12]
    name: wait-on ${{ matrix.OS }}
    runs-on: ${{ matrix.OS }}
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: dependencies
      run: npm ci
    - name: Test
      uses: cypress-io/github-action@v5
      with:
        wait-on: http://localhost:5173
        start: npm run dev

  workaround-1:
    strategy:
      fail-fast: false
      matrix:
        OS: [ubuntu-22.04, windows-2022, macos-12]
    name: wait-on fixed ${{ matrix.OS }}
    runs-on: ${{ matrix.OS }}
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: dependencies
      run: npm ci
    - name: Test
      uses: cypress-io/github-action@v5
      with:
        wait-on: http://localhost:5173
        start: npx vite --host

  wait-on-external:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: dependencies
      run: npm ci
    - name: Test
      uses: cypress-io/github-action@v5
      with:
        wait-on: npx wait-on http-get://localhost:5173 --config wait-on.config.json --timeout 10000 --verbose
        start: npm run dev

  debug:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: dependencies
      run: npm ci
    - name: Test
      uses: cypress-io/github-action@v5
      env:
        DEBUG: '@cypress/github-action, cypress:*'
      with:
        wait-on: http://localhost:5173
        start: npm run dev

  workaround-2:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: dependencies
      run: npm ci
    - name: Test
      uses: cypress-io/github-action@v5
      with:
        wait-on: http://ip6-localhost:5173
        start: npm run dev
